package io.github.gelaechter.util;

public enum Texts {
    STARTING,
    STARTED_IN_TIME,
    CLIENT_ADDRESS,
    ADMIN_ADDRESS,
    ADMIN_PASSWORD, ADMIN_PASSWORD_CHANGED,
    HOSTADDRESS_ERROR_ARTNET,
    NODE_IP_RESOLVE_ERROR,
    UNNAMED_USER,
    STOPPING_ARTNET,
    STOPPING_WEBSERVER,
    LOGFILE_ERROR,
    SHUTDOWN_ERROR,
    COUNTDOWN,
    LOGFOLDER_ERROR,
    LOGFILE_LOCATION,
    GENERAL_ERROR,
    UNIVERSE_PARSE_ERROR,
    PORT_ERROR,
    SETTINGS_WRITE_ERROR,
    SETTINGS_READ_ERROR,
    FILE_ERROR, PORT_CHANGE
}
